### ISSUE TITLE
Need setup instructions for Mac

### ISSUE THREAD

**Issue by maneesha** [PhillyPythonWorkshop/PhillyPythonWorkshop.github.io#10]
/frisetup/ links to setup pages for Linux, Mac, & Windows.  
I have not moved the Mac instructions from [OpenHatch](https://openhatch.org/wiki/Philadelphia_Python_Workshop/Setup) here because I don't know anything about Macs and can't verify/update instructions as needed.  

Any Mac users want to help?

**Comment by adityanatraj** [comment]
PR for this here: 

https://github.com/PhillyPythonWorkshop/PhillyPythonWorkshop.github.io/pull/11
