### ISSUE TITLE
Formatting page on setting up Python on Windows

### ISSUE THREAD

**Issue by maneesha** [PhillyPythonWorkshop/PhillyPythonWorkshop.github.io#4]
http://phillypythonworkshop.github.io/frisetupwindows/

Numbering is not continuous - needs to be fixed.

Sample header of what the start of the Python shell looks like is not formatted properly - needs to be fixed.  New lines don't work.

**Comment by maneesha** [comment]
Also on page  /fridaycheckoff 
numbering is not continuous - restarts after a code block

**Comment by FlipperPA** [comment]
Check my P.R. with new instructions for Windows - should be automagically numbered.
