### ISSUE TITLE
What text editor should we recommend?

### ISSUE THREAD

**Issue by maneesha** [PhillyPythonWorkshop/PhillyPythonWorkshop.github.io#6]
Sublime is my favorite and is the most powerful. It is also available across all three platforms (Mac, Linux, Windows).   However it is not free. It has a non-enforced license fee. So you could keep using it forever without paying but you'll get popups every few days reminding you.

**Comment by williln** [comment]
[Here](http://www.pyladies.com/resources/#text-editors) is the list that PyLadies recommends, if that's helpful.

**Comment by maneesha** [comment]
Thanks!  Our old curriculum offered a few choices.  I'm going back and forth about whether to offer a list like that, or to have everyone using the same text editor which would make setup easier.
